pipeline {
    agent {
        label 'MavenBuilder1'        
    }
    tools {
        maven 'jenkins-maven' // Use the name you defined in Global Tool Configuration
    }
     
    options {
        skipStagesAfterUnstable()
        
    }
    stages {
        stage('Build') {
            steps {
                retry(3)
                {
                sh 'mvn -B -DskipTests clean package'
                }    
                
            }
        }
        stage('Test') {
            
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
             
            
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
